server:
  port: 8081

spring:
  application:
    name: forecast-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

notification:
  service:
    url: http://NOTIFICATION-SERVICE

weather:
  api:
    key: "${WEATHER_API_KEY}"
    city: "${WEATHER_CITY}"
    hour:  "${WEATHER_HOUR:11}"
    rain-threshold: "${RAIN_THRESHOLD:40}"