server:
  port: 8081

spring:
  application:
    name: forecast-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true


weather:
  api:
    key: "${WEATHER_API_KEY}"
    city: "${WEATHER_CITY}"
    hour:  "${WEATHER_HOUR:11}"
    rain-threshold: "${RAIN_THRESHOLD:40}"