spring:
  application:
    name: RaEurekaServerApplication
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: debug
